# cask_args appdir: '/Applications'

# tap 'homebrew/bundle'

# brew 'cloudflared'
# brew 'imagemagick'
# brew 'spaceman-diff'
# brew 'wget'

# cask '1password'
# cask 'airtable'
# cask 'android-platform-tools'
# cask 'arq'
# cask 'diffusionbee'
# cask 'handbrake'
# cask 'messenger'
# cask 'notion-calendar'
# cask 'plex'
# cask 'sonos'
# cask 'transmission'
# cask 'raycast'
# cask 'warp'
# cask 'whatsapp'
# cask 'visual-studio-code'
# cask 'vlc'
# cask 'zed'
# cask 'zoom'
